[project]
name = "iac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-alicloud>=3.0.0,<4.0.0",
    "pulumi-command>=1.1.0",
]
